api_root_path: /
auth_path_prefix: /auth
auto_reload: false
basic_auth_pwd: null
basic_auth_realm: GHGA Data Portal
basic_auth_user: null
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
docs_url: /docs
host: 127.0.0.1
log_level: debug
openapi_url: /openapi.json
port: 8080
run_auth_adapter: false
service_name: auth_service
workers: 1
