add_as_data_stewards: []
api_ext_path: /api/auth
api_root_path: /
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  name: null
auth_ext_algs:
- RS256
- ES256
auth_ext_keys: null
auth_key: null
auth_map_claims: {}
auto_reload: true
basic_auth_credentials: []
basic_auth_realm: GHGA Data Portal
claims_collection: claims
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_name: user-management
db_url: '**********'
docs_url: /docs
host: 0.0.0.0
include_apis:
- users
log_level: debug
oidc_authority_url: https://proxy.aai.lifescience-ri.eu
oidc_client_id: ghga-data-portal
oidc_userinfo_endpoint: https://proxy.aai.lifescience-ri.eu/OIDC/userinfo
openapi_url: /openapi.json
organization_url: https://ghga.de
port: 8080
public_paths:
- /.well-known/*
- /service-logo.png
run_auth_adapter: false
service_name: auth_service
users_collection: users
workers: 1
