add_as_data_stewards: []
allow_read_paths:
- /.well-known/*
- /service-logo.png
allow_write_paths: []
api_ext_path: /api/auth
api_root_path: ''
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  id: null
  name: null
auth_ext_algs:
- RS256
- ES256
auth_ext_keys: null
auth_key: null
auth_map_claims: {}
auto_reload: true
basic_auth_credentials: null
basic_auth_realm: GHGA Data Portal
claims_collection: claims
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
csrf_token_bytes: 24
dataset_deletion_event_topic: metadata_datasets
dataset_deletion_event_type: dataset_deleted
db_connection_str: '**********'
db_name: dev-db
docs_url: /docs
generate_correlation_id: true
host: 0.0.0.0
include_apis:
- users
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: DEBUG
oidc_authority_url: https://proxy.aai.lifescience-ri.eu/
oidc_client_id: ghga-data-portal
oidc_userinfo_endpoint: https://proxy.aai.lifescience-ri.eu/OIDC/userinfo
openapi_url: /openapi.json
organization_url: https://ghga.de/
port: 8080
run_auth_adapter: false
service_instance_id: '1'
service_name: auth_service
session_id_bytes: 24
session_max_lifetime_seconds: 43200
session_timeout_seconds: 3600
totp_algorithm: sha1
totp_attempts_per_code: 3
totp_digits: 6
totp_encryption_key: null
totp_image: null
totp_interval: 30
totp_issuer: GHGA
totp_max_failed_attempts: 10
totp_secret_size: 32
totp_tolerance: 1
user_tokens_collection: user_tokens
users_collection: users
workers: 1
