api_root_path: /
auth_ext_algs:
- RS256
- ES256
auth_ext_keys: null
auth_int_keys: null
auto_reload: true
basic_auth_pwd: null
basic_auth_realm: GHGA Data Portal
basic_auth_user: null
claims_collection: claims
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_name: user-management
db_url: mongodb://mongodb:27017/
docs_url: /docs
host: 0.0.0.0
log_level: debug
oidc_authority_url: https://proxy.aai.lifescience-ri.eu
oidc_client_id: ghga-data-portal
openapi_url: /openapi.json
port: 8080
run_auth_adapter: false
service_name: auth_service
users_collection: users
workers: 1
