info:
  contact:
    email: helpdesk@ghga.de
    name: GHGA
  description: REST API for managing the GHGA users and user claims
  license:
    name: Apache 2.0
  title: User Management API
  version: 2.0.0a0
openapi: 3.1.0
paths:
  /health:
    get:
      description: Used to check that this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
      - health
tags:
- description: User data
  name: users
- description: User claims
  name: claims
