# Please only mention the non-default settings here:

auto_reload: true

host: 0.0.0.0

db_connection_str: mongodb://mongodb:27017/
db_name: "dev-db"

log_level: DEBUG

service_instance_id: "1"
kafka_servers: ["kafka:9092"]
