version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # [Choice] Python version: 3, 3.9, 3.10, 3.11
        VARIANT: 3.9
        PACKAGE_NAME: "auth_service"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    privileged: true

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # define environment variables
    environment:
      AUTH_SERVICE_HOST: "0.0.0.0"
      AUTH_SERVICE_PORT: "8080"
      AUTH_SERVICE_AUTO_RELOAD: "true"
      AUTH_SERVICE_DB_URL: mongodb://mongodb:27017/
      AUTH_SERVICE_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Please remove service dependencies that are not needed:
  mongodb:
    image: mongo:5.0.11
    restart: unless-stopped
    volumes:
      - mongo_fs:/data/db
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

volumes:
  mongo_fs: {}
