[project]
name = "auth_service"
version = "2.0.0-alpha.0"
description = "Authentication adapter and services used for the GHGA data portal"
dependencies = [
    "ghga-event-schemas==3.0.0",
    "ghga-service-commons[api,auth]>=3.0.3,<4",
    "hexkit[mongodb,akafka]>=2.1.0",
    "pynacl>=1.5,<2",
    "pyotp>=2.9,<3",
    "httpx>=0.25.2"
]

[project.urls]
Repository = "https://github.com/ghga-de/auth-service"

[project.scripts]
auth-service = "auth_service.__main__:run"

[tool.pytest.ini_options]
# the unit tests should always run before the integration tests
testpaths = [
    "tests/unit",
    "tests/integration"
]
