[project]
name = "auth_service"
version = "1.0.1"
description = "Authentication adapter and services used for the GHGA data portal"
dependencies = [
    "ghga-event-schemas==3.0.0",
    "ghga-service-commons[api,auth]>=2,<3",
    "hexkit[mongodb,akafka]>=2.1.0",
    "httpx>=0.25.2"
]

[project.urls]
Repository = "https://github.com/ghga-de/auth-service"

[project.scripts]
auth-service = "auth_service.__main__:run"
